(ns fedoras.sessions.one
  "SESSION ONE. What the animal does when the hound comes.

  One passage per animal, keyed by the animal's name, so the roster can
  be reordered and every passage still reaches its own animal. The
  reader rolled an animal earlier in the same scene; this is what it
  did when the hound came up the corridor for the ledger.

  Every session of the campaign gets a file like this one."
  (:require [fedoras.companions :as companions]
            [fedoras.sessions :as sessions]))

(def passages-by-animal
  {"Pigeon"
   (str "Two of the hounds come along the corridor making for the ledger, "
        "and the pigeon walks out into the middle of the floor, because "
        "that is where the crumbs would be. The front hound stops. It is "
        "a page-dog, and it does what a page-dog does, which is to look "
        "at a thing and imprint it on its own page so that the record can "
        "go back to whoever sent it. It looks at the pigeon. The pigeon "
        "takes one step sideways. The hound imprints the pigeon. The "
        "pigeon takes another step. The hound imprints the pigeon again, "
        "because the first imprint is now out of date.\n\n"
        "The pigeon walks up the hound's foreleg, onto its back, and "
        "stands there, looking round at the corridor from a slightly "
        "better height. The hound stands very still. It cannot imprint "
        "the pigeon, because the pigeon is behind its eyes, and it cannot "
        "imprint itself, because a page-dog has never been asked to "
        "record its own back. The second hound comes up beside it, looks "
        "at the first hound, and imprints that. The first hound does not "
        "turn round. It does not know how.\n\n"
        "Miles writes HOUND DETAINED BY PIGEON. Victor looks at the "
        "entry for a long moment, and approves it. It is the only thing "
        "Victor approves all evening.")

   "Giant Centipede"
   (str "The centipede goes up the front hound's foreleg and in at the "
        "shoulder, between one page and the next, and the hound stops. "
        "It stands very straight, the way you stand when there is "
        "something in your shirt.\n\n"
        "The hound is a record in progress. Every page inside it has an "
        "imprint on it — things it has looked at, things it has sniffed, "
        "things it has been told to remember — and the centipede is "
        "walking through all of them, in order, and eating as it goes. "
        "Victor starts reading the imprints out as the centipede passes "
        "them, because the numbers are in the corners and he can see "
        "them: forty-three, forty-seven, nine, a hundred and five. He "
        "gets the joke of it about four numbers in, and stops, and the "
        "centipede does not stop, because the centipede is not doing a "
        "joke.\n\n"
        "By the time it comes out at the tail the hound has no record "
        "left in it. It sits down in the corridor and begins to look at "
        "things, so that it can make a new record, which is what a "
        "page-dog does when its pages are empty. It is still looking at "
        "things when Victor calls tea. It is still looking at them when "
        "they come back. Miles asks what it has got to. Victor says it "
        "keeps imprinting the same stretch of corridor over and over, "
        "because it has nothing in it to tell it that it has already "
        "been here.")

   "Marmot"
   (str "The marmot sits up in the middle of the corridor to look at the "
        "hounds. The looking goes badly, so it whistles. The front hound "
        "stops. It was assembled by something that has read a great deal "
        "about dogs, and everything it has read agrees on what a dog does "
        "when it is whistled for. It turns, and trots back to the marmot, "
        "and sits down beside it at the wrong height, facing the same "
        "way. It imprints the marmot. Then it imprints the wall the "
        "marmot is looking at, because a page-dog records what is in "
        "front of it and the marmot is now in front of a wall.\n\n"
        "Victor lets this stand until the table starts laughing, and then "
        "for a good while after the laughing stops. The marmot has a "
        "dog. It whistles again, twice, short, and the hound gets up and "
        "goes off down the corridor at a trot, to record whatever a "
        "whistle tells a dog to record, which neither the hound nor "
        "Victor nor the module has ever specified. Miles asks how he is "
        "meant to record that. Victor says accurately.")

   "Cat"
   (str "The cat was at the door before the hounds were in the building. "
        "When the front hound reaches the storage room Miles has the "
        "ledger open on the floor between his knees, and the cat gets "
        "up, crosses the corridor without hurrying, steps onto the open "
        "ledger, turns round twice, and lies down on it.\n\n"
        "The hound has come to record the ledger. The cat is on the "
        "ledger. It walks up, lowers its head, and imprints the cat "
        "instead, because a page-dog records what it can see and what it "
        "can see is a cat. Victor lays it out in exactly those words and "
        "then stops talking, because everybody at the table has at some "
        "point needed something a cat was lying on. The hound tries the "
        "next page. The cat lays one paw across its muzzle, claws in, as "
        "you might keep a hand on a letter to stop it blowing away, and "
        "leaves it there.\n\n"
        "It stays like that for twenty minutes. At the end of them the "
        "hound goes, with a record that contains one cat and nothing "
        "else, and the cat is asleep, and Miles writes the rest of the "
        "evening on the back of his character sheet.")

   "Turkey"
   (str "The first hound barks once at the top of the stairs. Its bark "
        "is the sound of a rubber stamp coming down on a desk. The "
        "turkey gobbles back. The hound stamps again. The turkey gobbles "
        "again, louder, and fans its tail, and its head goes blue to "
        "white to red in the time it takes Victor to say so.\n\n"
        "Each time the hound stamps, the turkey answers, and each time "
        "the turkey answers the hound has to stamp again, because a "
        "stamp that has been answered has not been stamped. It imprints "
        "the turkey. It imprints the answer. Then it has to imprint the "
        "imprint, because the imprint is now out of date, and then the "
        "imprint of the imprint, and it is going to be doing this for a "
        "long time. Victor does both noises, for some time. The second "
        "hound, which is further back, turns round and goes home with a "
        "page that says only TURKEY.\n\n"
        "Then the first hound comes forward, and the turkey goes to meet "
        "it low with its wings out, the way turkeys go at people in car "
        "parks, and the hound — which has come up three floors of the "
        "Collegium without once being contradicted — backs away. Victor "
        "finishes the encounter in a whisper, because the turkey answers "
        "him too.")

   "Giant Badger"
   (str "The badger is under the corridor before the first hound "
        "reaches it. Victor says so, and then describes the corridor as "
        "though there were nothing under it, which is worse. The hound "
        "comes on with its nose down. Halfway along, the boards under "
        "its forefeet sag, and part, and it goes in to the shoulder, and "
        "something below takes hold of it, and it goes in the rest of "
        "the way.\n\n"
        "The boards settle. There is a scraping, going away, then a "
        "scraping, coming back, then quiet. The badger comes up beside "
        "the storage room door with plaster in its fur, sneezes, and "
        "sits. The second hound stops at the edge of the hole and "
        "imprints the hole. Then it turns round and goes back the way it "
        "came, because a page-dog records what it has found, and what it "
        "has found is that the corridor has a way down. Miles asks where "
        "the first hound is. Victor says under the floor. Miles asks "
        "where under the floor. Victor says with the rest of the "
        "records, and Miles, slowly, writes FILED.")

   "Giant Weasel"
   (str "When the hounds come round the corner the weasel begins to "
        "dance. Derek knows the name for it and says it: the war dance. "
        "The weasel leaps sideways, and backwards, and straight up, "
        "twists in the air and lands facing somewhere else, and does it "
        "again, faster, back arched and mouth open, its whole length "
        "thrown about as though something invisible has it by the "
        "tail.\n\n"
        "Victor stands up to show them. He is broad and the hat is tall, "
        "and the war dance, performed by Victor in Room 3C, takes the "
        "full width of the room, and at each position the hat arrives a "
        "moment after he does. Simon cannot look away. Neither can the "
        "hounds. The front hound is trying to imprint the weasel and it "
        "cannot, because the weasel is never in the same place as the "
        "last page it filled. By the time the weasel reaches it, the "
        "hound has thirty pages of nothing in particular and one at the "
        "end, in progress, with the weasel at its throat.")

   "Fox"
   (str "The fox gets to the ledger before the hounds do, which is the "
        "hounds' own trick, and takes it out of Miles's hands so gently "
        "that his hands are still holding the shape of it. Then it runs. "
        "It goes past the front hound close enough to touch, and the "
        "hound turns and goes after it, because the ledger is what it "
        "came for and the ledger is leaving down the corridor in the "
        "mouth of a fox. The second hound imprints the fox, and the "
        "ledger, and the corridor, and turns and goes back to tell "
        "somebody.\n\n"
        "The first goes down the stairwell after the fox. Victor calls "
        "the chase by floors: third, second, first, and then a floor the "
        "building does not have. The fox comes back alone, with a page "
        "in its mouth that is not the ledger page and is not the "
        "hound's. It sets the page down at {pc}'s feet. Miles reads it. "
        "It says the fox was here, and it says where the fox went, and "
        "it is in a hand none of them recognise, and it is the first "
        "thing all evening that was not written by someone at the "
        "table.")

   "Wolverine"
   (str "The wolverine is lying across the doorway when the front hound "
        "arrives, and it goes on lying there until the hound is close "
        "enough to make a mistake. Then it takes the hound's front leg "
        "off at the shoulder — and a leg, on a page-dog, is pages — "
        "turns, and carries the leg into the storage room, and puts it "
        "under the bottom shelf, where nobody can reach it.\n\n"
        "The hound stands in the corridor missing a leg. It cannot "
        "proceed. It was assembled to proceed, and the pages it needs "
        "are under a shelf in another room, and it was not assembled to "
        "look under shelves. It stands there. It keeps standing there. "
        "The second hound comes up beside it, imprints it, and waits to "
        "see what the first hound will do, which turns out to be "
        "nothing, indefinitely. The wolverine comes back out, sits down "
        "in the doorway with its chin on its paws, and looks at Miles. "
        "At the ledger in Miles's lap. At the paper. Miles holds the "
        "ledger against his chest. Victor lets them listen to the strip "
        "light.")

   "Dog"
   (str "The dog hears the hounds before anybody else does and goes to "
        "meet them with its tail up, as one dog goes to meet another in "
        "a park. A yard away it stops and bows: elbows down, back end "
        "up, the invitation every dog knows. The front hound stops as "
        "well. It was assembled out of everything ever written down "
        "about dogs, and none of it mentioned this. It studies the dog. "
        "Then it lowers its front end, stiffly, at the wrong height, "
        "into something with the outline of a bow. It imprints the bow. "
        "The dog, delighted, bows back. The hound imprints the answer, "
        "because the answer is a bow, and a bow that has been answered "
        "is not the same bow. So it bows again. And the dog bows back.\n\n"
        "For a minute of table time the two of them bow to each other in "
        "the corridor, and Victor describes every bow, and nobody at the "
        "table says a word. The second hound, further back, walks past "
        "the whole thing without looking, because it has been sent for "
        "the ledger, and it is the only page-dog in the corridor that "
        "is. It reaches Miles while the first hound and the dog are "
        "still bowing, and Miles has to decide whether to shut the "
        "ledger or keep watching.")

   "Python"
   (str "The python is on the beam over the corridor. Nobody saw it go "
        "up there. Victor says it has been there since the tea. The "
        "front hound passes underneath with its nose to the floor, cold "
        "as paper is cold, and the python, which has spent the evening "
        "looking for warmth, lets it go by. Then the hound reaches "
        "Miles, who is warm, and lowers its head to the ledger in "
        "Miles's lap, and for a moment the cold thing and the warm thing "
        "are in the same place.\n\n"
        "The python comes down on both. It lets go of Miles at once. It "
        "keeps the hound. Victor describes the first fold, and the "
        "second, and the sound of a page being folded along a line where "
        "it has never been creased. Derek says paper can only be folded "
        "seven times. Victor says yes, and describes the eighth. The "
        "second hound stops at the bottom of the corridor and imprints "
        "the python, and imprints the hound inside it, and turns and "
        "goes back, because a page-dog that has seen a thing folded "
        "eight times has seen enough to report. When the python lets go "
        "at last, the hound opens out slowly on the floor with the "
        "creases still in it, and every imprint inside it is now on the "
        "wrong side of a fold, and it goes back down the corridor "
        "unable to say a single thing it came to say.")

   "Mule"
   (str "The hounds have come for the ledger, and the ledger is in the "
        "mule's pannier, because by now everything is. The front hound "
        "goes to the mule's left side. The mule turns, so that the hound "
        "is at its back end. The hound goes round to the right. The mule "
        "turns. The hound goes round again and the mule turns again, "
        "patiently, on the spot, like a turntable, and they go round "
        "like that in the corridor while Victor narrates each "
        "quarter-turn in the same level voice, until Simon has to put "
        "his head down on the table.\n\n"
        "The second hound is standing back, imprinting every quarter. It "
        "has been told to find the ledger, and what it has found is a "
        "mule, from four angles, and it has no way of knowing that the "
        "four angles are the same mule, so its report is going to be "
        "very long and is not going to mention a ledger at all. Then "
        "Victor rolls a die in front of the screen, in the open, for the "
        "first time all evening. It comes up twenty. He describes the "
        "kick. There is only one. The first hound leaves the corridor by "
        "the far end at some height above the floor. The mule settles, "
        "and declines to move from the spot for the rest of the night, "
        "and the party has to unload it where it stands. Miles writes "
        "MULE. DECLINED TO PROCEED.")

   "Lynx"
   (str "The lynx is on top of the door frame when the hounds come "
        "along the corridor. The first hound passes under it, and the "
        "lynx drops. It is on the hound's back with its teeth in the "
        "throat before Victor has finished the sentence about where it "
        "went, and Victor finishes the sentence anyway.\n\n"
        "Along the underside of the hound's throat, from one side to the "
        "other, there is a line of small holes. Victor mentions them "
        "only now, as though they had been there all along: a "
        "perforation, of the sort a form has where you are meant to "
        "tear. The lynx tears along it, cleanly, the whole way. The "
        "piece that comes away is the stub, the part at the bottom of a "
        "page where the imprint is signed, and the lynx carries it over "
        "and sets it down in front of Miles. The rest of the hound "
        "stands in the corridor for a moment, unsigned, and then goes "
        "back the way it came. The second hound imprints the stub. The "
        "lynx watches it do it. By the time Miles has filed the stub the "
        "lynx is on top of the door frame again, washing a forepaw, and "
        "the second hound is walking very slowly backwards down the "
        "corridor, keeping the door frame in view.")

   "Ape"
   (str "The hounds come up the corridor with their heads low, making "
        "for whoever in the building is about to write something down, "
        "and that is the ape. The ape looks at the front hound, and at "
        "the pencil, and at the hound. Then it takes the hound by the "
        "scruff, turns it over, and smooths it out flat on the floor, as "
        "you would smooth a form on a counter, and begins to fill it in.\n\n"
        "Victor describes the tip of the ape's tongue at the corner of "
        "its mouth, and the pencil moving from box to box. He does not "
        "describe what it writes. When it has finished, the ape signs at "
        "the bottom of the hound, and the hound gets up. A completed "
        "form has somewhere to be. It sets off back down the corridor at "
        "a brisk trot, towards whatever office receives it, and does not "
        "look round. The second hound watches it go. Then it looks at "
        "the ape, and the ape looks back at it, and the ape is still "
        "holding the pencil. The second hound turns round and follows "
        "the first, and neither of them reports anything else for the "
        "rest of the evening. Miles asks what the ape wrote. Victor says "
        "it must have been true, or the hounds would have stayed.")

   "Horse"
   (str "The horse comes up the corridor to meet the hounds. There is "
        "not room for it. It comes anyway, ears flat, tail swinging, "
        "its shoulders touching both walls. Victor stands. He names what "
        "the horse does next, because there is a name for it: a "
        "capriole. The horse leaves the ground with all four feet at "
        "once, in a corridor on the third floor, and at the top of the "
        "leap it kicks out behind with both hind legs, level, the kick "
        "the old riding schools still teach long after the battles it "
        "was meant for.\n\n"
        "Derek knows the word from a film and mouths it along with him. "
        "At the top of the leap the front hound is behind the horse. "
        "Afterwards the front hound is at the far end of the corridor in "
        "a number of pieces, like a drawer of files dropped down a "
        "stairwell, and the pages have come apart in flight and are "
        "scattered the whole length of the corridor, each one an imprint "
        "of a different moment of a horse, and none of them in order. "
        "The second hound walks the corridor and picks them up. It is "
        "still picking them up when the party leaves. The horse comes "
        "down. Plaster sifts from the ceiling where its ears touched. It "
        "stands blowing, and then turns its head and waits for {pc} to "
        "get on.")

   "Moose"
   (str "The moose is in the corridor facing the party when the hounds "
        "come up the stairs behind it. It cannot turn round. The "
        "corridor will not let it. The whole table works this out at "
        "once, and then works out the only other thing a moose in a "
        "corridor can do.\n\n"
        "It reverses. Derek, without being asked, makes the noise a "
        "lorry makes when it is reversing, and keeps making it, and "
        "Victor lets him, and narrates over the top: the moose going "
        "backwards down the corridor at speed, blind, antlers scraping "
        "both walls and bringing the plaster down, and the hounds at the "
        "far end looking up at a very large animal coming towards them "
        "from the wrong end. The beeping stops when the moose does. "
        "There is a long pause. The moose, having backed the whole "
        "length of the corridor, stands at the far end, still facing the "
        "party, entirely calm. Somewhere underneath it is the first "
        "hound, and its last imprint, on the last page inside it, is a "
        "moose coming at it from the wrong end. The second hound "
        "imprints the whole of it, including the moose, including the "
        "corridor, including the noise, which Victor does once more for "
        "the record.")

   "Wyrmling"
   (str "The hounds come up the corridor and stop a yard short of "
        "{pc}, and lower their heads, and sniff at the pack. The "
        "wyrmling opens one eye. Victor stops talking. He takes the hat "
        "off, which nobody at the table has ever seen him do, and sets "
        "it on the floor beside his chair, and then he describes the "
        "breath. It is short. It is fire.\n\n"
        "The front hound is paper and three years of dust, and it goes "
        "up the way a letter goes up in a grate, all at once, bright at "
        "the edges, and then it is ash standing in the shape of a dog. "
        "Derek says fire could mean red, or gold, or brass. Victor says "
        "yes. The second hound imprints the fire, and the ash, and turns "
        "and leaves, and Victor does not stop it. The eye closes and the "
        "wyrmling goes back to sleep. Then the ash moves. It stands up "
        "in the shape of the hound, grey and soft and exact, turns "
        "round, and goes back down the corridor the way it came, and it "
        "leaves no footprints in the dust. It has no imprints left in "
        "it, because it has no pages, and it is going home to report "
        "whatever an ash hound reports, which is not going to be "
        "anything useful to anybody.")

   "Falcon"
   (str "As soon as the hounds are on the stairs the falcon goes up "
        "the stairwell, up past four floors of banister and out of the "
        "light, and for a while there is nothing but the front hound "
        "coming along the corridor towards Miles. Then Victor does the "
        "noise with his mouth. It starts high and comes down the "
        "stairwell faster than anything can fall.\n\n"
        "The falcon hits the front hound with a closed foot at the "
        "bottom of the stoop, and the hound comes apart. It goes up like "
        "a ream of paper thrown at a ceiling and comes down over the "
        "whole corridor, sheet after sheet, and the falcon is on the "
        "banister before the last of it lands. Miles picks up a sheet. "
        "It is in his handwriting. It is the page he wrote tonight, word "
        "for word until the last line, and the last line has been "
        "changed. Where Miles wrote NOT APPROVED, it says APPROVED. He "
        "picks up another. It is the same page. They all are. The second "
        "hound walks up and imprints the falcon, and the falcon lets it, "
        "and does not look at it. Then the second hound walks back down "
        "the corridor with a report that says FALCON and nothing else, "
        "because it cannot read, and its master can.")

   "Wolf"
   (str "The wolf puts itself between {pc} and the hounds, head low, as "
        "it stood when it came out of the cage, and waits. The front "
        "hound comes on. Behind it, at the top of the stairwell, the "
        "light goes out. Victor tells them what the hound hears: claws "
        "on lino, several sets, none in any hurry. It turns its head. "
        "Nothing comes into the light.\n\n"
        "It looks back at the wolf, which has not moved, and does not "
        "need to, because it knows exactly what is behind it and does "
        "not have to look. The hound bolts back the way it came. The "
        "second hound does not bolt. It walks very calmly to the wolf, "
        "and imprints the wolf, and then walks to the light and imprints "
        "the light, and then walks back and imprints the wolf again, "
        "because the light was already in the wolf's report and it wants "
        "the two of them on the same page. The wolf watches it do all of "
        "this. Then the second hound walks back down the corridor the "
        "way it came, and the wolf walks to {pc} and sits, and there is "
        "paper caught in the fur at its throat. Miles asks what he "
        "should record. Victor says one wolf.")

   "Bear"
   (str "The doorway of the storage room goes dark, and it takes the "
        "table a moment to understand that the dark is the bear, sitting "
        "in it. The hounds come along the corridor and stop. Nothing "
        "they were assembled from has anything to say about this. The "
        "bear stands. It goes up and up, until its head is against the "
        "ceiling and its forepaws hang in front of its chest like a man "
        "holding his gloves, and it looks down at the hounds, and the "
        "hounds look up.\n\n"
        "The front hound imprints the bear. Then it imprints the bear "
        "again, because the bear is taller than the page. Then it "
        "imprints the bear's left forepaw, and then the right, and then "
        "the ceiling the bear has reached, and then it stops, because it "
        "has run out of pages and the bear is not finished being "
        "recorded. Victor brings his hand down flat on the folding "
        "table. The tin of dice jumps. The four bottle caps on the pizza "
        "box jump, and one of them rolls off onto the floor. Miles asks "
        "what the modifiers are. Victor says the modifier is a bear. "
        "When the bear lifts its paw the two hounds are flat, which is "
        "how they began, and they slide away down the corridor over the "
        "dust like letters pushed under a door.")})

(def encounters
  "Face on the die to passage, derived from the roster so the two can
  never disagree about which animal is which."
  (into (sorted-map)
        (map (fn [[face {:keys [animal]}]]
               [face (get passages-by-animal animal)]))
        companions/roster))

(defn animals-without-passages
  "Animals on the roster this session has nothing written for. Empty
  when the file is finished, and worth checking in every new session
  file before it ships."
  []
  (->> (vals companions/roster)
       (map :animal)
       (remove #(contains? passages-by-animal %))
       vec))

(defn what-it-did
  "The passage for whichever animal the reader rolled."
  []
  (sessions/passage "one" encounters))